module.exports = [
    ["get a", 'null'],
    ['get a b', 'ERROR: Syntax error'],
    ['set a asd', 'OK'],
    ['set a as as', 'ERROR: Syntax error'],
    ['get a', '"asd"'],
    ['rpush a 2', 'ERROR: This key does not hold a list'],
    ['rpush a', 'ERROR: Syntax error'],
    ['rpush b 1 2', '2'],
    ["get b", 'ERROR: This key does not hold a string'],
    ['rpop b 2', 'ERROR: Syntax error'],
    ['rpop b', '"2"'],
    ['rpush b 3 4 a', '4'],
    ['lpop b 2', 'ERROR: Syntax error'],
    ['lpop b', '"1"'],
    ['lpop b', '"3"'],
    ['lpop b', '"4"'],
    ['lpop b', '"a"'],
    ['lpop b', 'null'],
    ['rpop b', 'null'],
    ['lrange b 3 4 a', 'ERROR: Syntax error'],
    ['lrange b 3 4', '[]'],
    ['rpush b x y "za za"', '3'],
    ['lrange b 5 10', '[]'],
    ['lrange b 0 2', '["x","y","za za"]'],
    ['sadd a', 'ERROR: Syntax error'],
    ['sadd a 2', 'ERROR: This key does not hold a set'],
    ['sadd c 2 3', '2'],
    ['sadd c 2 3', '0'],
    ['sadd c "2" 1', '1'],
    ['scard c "2" 1', 'ERROR: Syntax error'],
    ['scard c', '3'],
    ['smembers c "2" 1', 'ERROR: Syntax error'],
    ['smembers c', '["2","3","1"]'],
    ['srem c', 'ERROR: Syntax error'],
    ['srem c 2', '1'],
    ['srem c 2', '0'],
    ['srem c 3 1', '2'],
    ['scard c', '0'],
    ['sadd c a b', '2'],
    ['sinter', 'ERROR: Syntax error'],
    ['sinter a b c', 'ERROR: Key a does not hold a set'],
    ['sinter u b c', 'ERROR: Key b does not hold a set'],
    ['sinter u c', '["a","b"]'],
    ['sadd d a b c', '3'],
    ['sinter d c', '["a","b","c"]'],
]